<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use Illuminate\Database\Seeder;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ingredients = [
            [
                'name' => 'Buzaliszt',
                'slug' => 'buzaliszt',
                'sku' => 'ING-BUZALISZT',
                'unit' => 'g',
                'estimated_unit_cost' => 469,
                'current_stock' => 60000,
                'minimum_stock' => 5000,
                'is_active' => true,
            ],
            [
                'name' => 'Rozs liszt',
                'slug' => 'rozs-liszt',
                'sku' => 'ING-ROZSLISZT',
                'unit' => 'g',
                'estimated_unit_cost' => 1519,
                'current_stock' => 18000,
                'minimum_stock' => 3000,
                'is_active' => true,
            ],
            [
                'name' => 'Só',
                'slug' => 'so',
                'sku' => 'ING-SO',
                'unit' => 'g',
                'estimated_unit_cost' => 1500,
                'current_stock' => 5000,
                'minimum_stock' => 1000,
                'is_active' => true,
            ],
            [
                'name' => 'Cukor',
                'slug' => 'cukor',
                'sku' => 'ING-CUKOR',
                'unit' => 'g',
                'estimated_unit_cost' => 314,
                'current_stock' => 10000,
                'minimum_stock' => 1000,
                'is_active' => true,
            ],
            [
                'name' => 'Eleszto',
                'slug' => 'eleszto',
                'sku' => 'ING-ELESZTO',
                'unit' => 'g',
                'estimated_unit_cost' => 25,
                'current_stock' => 450,
                'minimum_stock' => 500,
                'is_active' => true,
            ],
            [
                'name' => 'Vaj',
                'slug' => 'vaj',
                'sku' => 'ING-VAJ',
                'unit' => 'g',
                'estimated_unit_cost' => 1500,
                'current_stock' => 20000,
                'minimum_stock' => 2000,
                'is_active' => true,
            ],
            [
                'name' => 'Tej',
                'slug' => 'tej',
                'sku' => 'ING-TEJ',
                'unit' => 'ml',
                'estimated_unit_cost' => 199,
                'current_stock' => 25000,
                'minimum_stock' => 2500,
                'is_active' => true,
            ],
            [
                'name' => 'Tojas',
                'slug' => 'tojas',
                'sku' => 'ING-TOJAS',
                'unit' => 'g',
                'estimated_unit_cost' => 99,
                'current_stock' => 12000,
                'minimum_stock' => 1000,
                'is_active' => true,
            ],
            [
                'name' => 'Víz',
                'slug' => 'viz',
                'sku' => 'ING-VIZ',
                'unit' => 'ml',
                'estimated_unit_cost' => 1,
                'current_stock' => 50000,
                'minimum_stock' => 10000,
                'is_active' => true,
            ],
            [
                'name' => 'Anyakovász',
                'slug' => 'anyakovasz',
                'sku' => 'ING-ANYAKOVASZ',
                'unit' => 'g',
                'estimated_unit_cost' => 250,
                'current_stock' => 500,
                'minimum_stock' => 100,
                'is_active' => true,
            ],
            [
                'name' => 'Aktív kovász',
                'slug' => 'aktiv-kovasz',
                'sku' => 'ING-AKTIV-KOVASZ',
                'unit' => 'g',
                'estimated_unit_cost' => 250,
                'current_stock' => 8000,
                'minimum_stock' => 500,
                'is_active' => true,
            ],
            [
                'name' => 'Aktív kovász (általános)',
                'slug' => 'kovasz',
                'sku' => 'ING-KOVASZ',
                'unit' => 'g',
                'estimated_unit_cost' => 250,
                'current_stock' => 8000,
                'minimum_stock' => 500,
                'is_active' => true,
            ],
            [
                'name' => 'BL80 kenyérliszt',
                'slug' => 'bl80-kenyerliszt',
                'sku' => 'ING-BL80-KENYERLISZT',
                'unit' => 'g',
                'estimated_unit_cost' => 520,
                'current_stock' => 25000,
                'minimum_stock' => 5000,
                'is_active' => true,
            ],
            [
                'name' => 'Kenyérliszt',
                'slug' => 'kenyerliszt',
                'sku' => 'ING-KENYERLISZT',
                'unit' => 'g',
                'estimated_unit_cost' => 540,
                'current_stock' => 25000,
                'minimum_stock' => 5000,
                'is_active' => true,
            ],
            [
                'name' => 'Búzakenyérliszt',
                'slug' => 'liszt',
                'sku' => 'ING-LISZT',
                'unit' => 'g',
                'estimated_unit_cost' => 500,
                'current_stock' => 60000,
                'minimum_stock' => 5000,
                'is_active' => true,
            ],
            [
                'name' => 'Teljes kiőrlésű liszt',
                'slug' => 'teljes-kiorlesu-liszt',
                'sku' => 'ING-TELJES-KIORLESU-LISZT',
                'unit' => 'g',
                'estimated_unit_cost' => 620,
                'current_stock' => 10000,
                'minimum_stock' => 2000,
                'is_active' => true,
            ],
            [
                'name' => '00 liszt',
                'slug' => '00-liszt',
                'sku' => 'ING-00-LISZT',
                'unit' => 'g',
                'estimated_unit_cost' => 650,
                'current_stock' => 50000,
                'minimum_stock' => 5000,
                'is_active' => true,
            ],
            [
                'name' => 'Olívaolaj',
                'slug' => 'olivaolaj',
                'sku' => 'ING-OLIVAOLAJ',
                'unit' => 'g',
                'estimated_unit_cost' => 3500,
                'current_stock' => 8000,
                'minimum_stock' => 800,
                'is_active' => true,
            ],
            [
                'name' => 'Rozmaring',
                'slug' => 'rozmaring',
                'sku' => 'ING-ROZMARING',
                'unit' => 'g',
                'estimated_unit_cost' => 9000,
                'current_stock' => 1000,
                'minimum_stock' => 100,
                'is_active' => true,
            ],
            [
                'name' => 'Paradicsom',
                'slug' => 'paradicsom',
                'sku' => 'ING-PARADICSOM',
                'unit' => 'g',
                'estimated_unit_cost' => 900,
                'current_stock' => 5000,
                'minimum_stock' => 500,
                'is_active' => true,
            ],
            [
                'name' => 'Fokhagyma',
                'slug' => 'fokhagyma',
                'sku' => 'ING-FOKHAGYMA',
                'unit' => 'g',
                'estimated_unit_cost' => 2200,
                'current_stock' => 2000,
                'minimum_stock' => 200,
                'is_active' => true,
            ],
            [
                'name' => 'Barna cukor',
                'slug' => 'barna-cukor',
                'sku' => 'ING-BARNA-CUKOR',
                'unit' => 'g',
                'estimated_unit_cost' => 520,
                'current_stock' => 10000,
                'minimum_stock' => 1000,
                'is_active' => true,
            ],
            [
                'name' => 'Fahéj',
                'slug' => 'fahéj',
                'sku' => 'ING-FAHEJ',
                'unit' => 'g',
                'estimated_unit_cost' => 9000,
                'current_stock' => 2000,
                'minimum_stock' => 200,
                'is_active' => true,
            ],
            [
                'name' => 'Holland kakaópor',
                'slug' => 'kakao',
                'sku' => 'ING-KAKAO',
                'unit' => 'g',
                'estimated_unit_cost' => 4500,
                'current_stock' => 5000,
                'minimum_stock' => 500,
                'is_active' => true,
            ],
            [
                'name' => 'Méz',
                'slug' => 'mez',
                'sku' => 'ING-MEZ',
                'unit' => 'g',
                'estimated_unit_cost' => 2600,
                'current_stock' => 5000,
                'minimum_stock' => 500,
                'is_active' => true,
            ],
            [
                'name' => 'Mák',
                'slug' => 'mak',
                'sku' => 'ING-MAK',
                'unit' => 'g',
                'estimated_unit_cost' => 3200,
                'current_stock' => 3000,
                'minimum_stock' => 300,
                'is_active' => true,
            ],
            [
                'name' => 'Szezámmag',
                'slug' => 'szezammag',
                'sku' => 'ING-SZEZAMMAG',
                'unit' => 'g',
                'estimated_unit_cost' => 2800,
                'current_stock' => 3000,
                'minimum_stock' => 300,
                'is_active' => true,
            ],
        ];

        foreach ($ingredients as $item) {
            Ingredient::query()->updateOrCreate(
                ['slug' => $item['slug']],
                [
                    'name' => $item['name'],
                    'sku' => $item['sku'],
                    'unit' => $item['unit'],
                    'estimated_unit_cost' => $item['estimated_unit_cost'],
                    'current_stock' => $item['current_stock'],
                    'minimum_stock' => $item['minimum_stock'],
                    'is_active' => $item['is_active'],
                    'notes' => null,
                ],
            );
        }
    }
}
