/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "preferences.locale": [],
    "home": [],
    "weekly-menu": [],
    "about": [],
    "cart.index": [],
    "cart.items.store": [],
    "cart.items.update": [
        {
            "name": "productId",
            "required": true
        }
    ],
    "cart.items.destroy": [
        {
            "name": "productId",
            "required": true
        }
    ],
    "cart.clear": [],
    "checkout.index": [],
    "checkout.store": [],
    "orders.success": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "conversion-events.store": [],
    "register": [],
    "register.store": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "account": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "admin.dashboard": [],
    "admin.categories.index": [],
    "admin.categories.store": [],
    "admin.categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.index": [],
    "admin.users.store": [],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.temporary-permissions.store": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.temporary-permissions.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        },
        {
            "name": "temporaryPermission",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.discounts.store": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.discounts.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        },
        {
            "name": "discount",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.discounts.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        },
        {
            "name": "discount",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.index": [],
    "admin.products.store": [],
    "admin.products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.ingredients.store": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.ingredients.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        },
        {
            "name": "productIngredient",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.ingredients.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        },
        {
            "name": "productIngredient",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.recipe-steps.store": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.recipe-steps.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        },
        {
            "name": "recipeStep",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.recipe-steps.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        },
        {
            "name": "recipeStep",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.ingredients.index": [],
    "admin.ingredients.store": [],
    "admin.ingredients.update": [
        {
            "name": "ingredient",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.ingredients.destroy": [
        {
            "name": "ingredient",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.recipes.index": [],
    "admin.production-plans.index": [],
    "admin.production-plans.store": [],
    "admin.production-plans.update": [
        {
            "name": "productionPlan",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.production-plans.destroy": [
        {
            "name": "productionPlan",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.weekly-menus.index": [],
    "admin.weekly-menus.store": [],
    "admin.weekly-menus.update": [
        {
            "name": "weeklyMenu",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.weekly-menus.destroy": [
        {
            "name": "weeklyMenu",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.weekly-menus.publish": [
        {
            "name": "weeklyMenu",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.weekly-menus.unpublish": [
        {
            "name": "weeklyMenu",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.index": [],
    "admin.orders.show": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.status.update": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.index": [],
    "admin.roles.show": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.store": [],
    "admin.roles.update": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.destroy": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.roles.permissions.sync": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.user-roles.index": [],
    "admin.users.roles.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.permissions.index": [],
    "admin.permissions.sync": [],
    "admin.permissions.show": [
        {
            "name": "permissionName",
            "required": true
        }
    ],
    "admin.audit-logs.index": [],
    "admin.audit-logs.show": [
        {
            "name": "activity",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.security-dashboard.index": [],
    "admin.security-dashboard.events.show": [
        {
            "name": "activity",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.conversion-analytics.index": [],
    "admin.profit-dashboard.index": [],
    "admin.ceo-dashboard.index": [],
    "admin.suppliers.index": [],
    "admin.suppliers.store": [],
    "admin.suppliers.update": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.suppliers.destroy": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.ingredient-supplier-terms.index": [],
    "admin.ingredient-supplier-terms.store": [],
    "admin.ingredient-supplier-terms.update": [
        {
            "name": "ingredientSupplierTerm",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.ingredient-supplier-terms.destroy": [
        {
            "name": "ingredientSupplierTerm",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.purchases.index": [],
    "admin.purchases.show": [
        {
            "name": "purchase",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.purchases.store": [],
    "admin.purchases.update": [
        {
            "name": "purchase",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.purchases.post": [
        {
            "name": "purchase",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.purchases.cancel": [
        {
            "name": "purchase",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.procurement-intelligence.index": [],
    "admin.procurement-intelligence.purchase-drafts.store": [],
    "admin.inventory.index": [],
    "admin.inventory.waste.store": [],
    "admin.inventory.adjustments.store": [],
    "admin.stock-counts.index": [],
    "admin.stock-counts.show": [
        {
            "name": "stockCount",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.stock-counts.store": [],
    "admin.stock-counts.update": [
        {
            "name": "stockCount",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.stock-counts.close": [
        {
            "name": "stockCount",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
